spring:
  cloud:
    gateway:
      routes:

      - id: productregistration_passthrough
        uri: https://api.cte.noncde.paymark.io/productregistration
        predicates:
          - Path=/productregistration_passthrough/**
        filters:
          - RewritePath=/productregistration_passthrough/(?<segment>.*), /productregistration/${segment}
          - name: PreSteps
            args:
              name:
                - SetContext
                - CreateLogMessage
                - CallSplunk
                - RequestHeaderValidation
                - PathAndTokenValidation
                - SetAuthToHeader
                - CallOutEndpoint

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: info

splunk:
  host: http-inputs-pm.splunkcloud.com
  path: services
  collector: collector
  token: your-splunk-token

PreFlow:
  SetContext: -3
  CallSplunk: -2
  SetAuthToHeader: -1

PostFlow:
  CallSplunk: 1

